### ISSUE TITLE
Snackbar plugin Switch sheet stopped working

### ISSUE THREAD

**Issue by PsychodelEKS** [NickM-27/Nick-Nack-Tasker-Plugin-Docs#1]
After last two updates of Snackbar plugin, switch sheet stopped working for me. ss_command() always return false for all switches. I did not mangle with configuration.

**Comment by NickM-27** [comment]
Interesting, thanks for the report. I will check this out and hopefully fix in an update later today.

**Comment by NickM-27** [comment]
Update going out now

**Comment by PsychodelEKS** [comment]
The switches state is reported fine after the update, but their state is not set correctly to provided values when the pop-up is opened

**Comment by PsychodelEKS** [comment]
@NickM-27 ping =)

**Comment by NickM-27** [comment]
Thanks I'll check this out today
